name: Continuous Integration
on:
  push:
    branches: [ "project" ]
  pull_request:
    branches: [ "project" ]
  workflow_dispatch:
  
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev build-essential

      - name: Install Packages
        working-directory: Train
        run: make install

      - name: Format
        working-directory: Train
        run: make format

      - name: Train
        working-directory: Train
        run: make train

      - name: Evaluation
        working-directory: Train
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval

      - name: Update Branch
        working-directory: Train
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
